kind: Deployment
apiVersion: apps/v1
metadata:
  name: airliner
  namespace: airport-system
  labels:
    app: airliner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airliner
  template:
    metadata:
      labels:
        app: airliner
    spec:
      containers:
        - name: airliner
          image: ghcr.io/joranbergfeld/airport-system-airliner/airliner:latest
          ports:
            - containerPort: 9002
              protocol: TCP
          resources: { }
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
