apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: airliner
  name: airliner
  namespace: airport-system
spec:
  port:
    targetPort: 9002-tcp
  to:
    kind: Service
    name: airliner
    weight: 100
