apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-credentials-external-secret
  namespace: airport-system
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: SecretStore
    name: azure-secret-store
  target:
    name: spring-boot-database-credentials-secret
    creationPolicy: Owner
  data:
    - secretKey: azure-postgres-database-username
      remoteRef:
        key: azure-postgres-database-username
    - secretKey: azure-postgres-database-username
      remoteRef:
        key: azure-postgres-database-password