apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-credentials-external-secret
  namespace: airport-system
  labels:
    application-system: airport-system
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-secret-store
  target:
    name: spring-boot-database-credentials-secret
    creationPolicy: Owner
  data:
    - secretKey: SPRING_DATASOURCE_USERNAME
      remoteRef:
        key: azure-postgres-database-username
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: azure-postgres-database-password
    - secretKey: SPRING_DATASOURCE_URL
      remoteRef:
        key: azure-postgres-database-url