apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-secret-store
  namespace: airport-system
spec:
  provider:
    azurekv:
      tenantId: "3e748433-8351-402d-b419-e9d688c75dbe"
      vaultUrl: https://ocp-key-vault-1.vault.azure.net/
      authSecretRef:
        clientId:
          name: azure-secret-sp
          key: ClientID
        clientSecret:
          name: azure-secret-sp
          key: ClientSecret
