apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    application-system: airport-system
    prometheus-scraping: spring-boot-actuator
  name: spring-boot-actuator-monitor
  namespace: airport-system
spec:
  endpoints:
    - interval: 30s
      path: /actuator/prometheus
      port: 8080-tcp
  namespaceSelector:
    matchNames:
      - airport-system
  selector:
    matchLabels:
      prometheus-scraping: spring-boot-actuator