kind: ConfigMap
apiVersion: v1
metadata:
  name: spring-boot-app-config-map
  namespace: airport-system
  labels: 
    application-system: airport-system
data:
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: INFO
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
  SPRING_JPA_HIBERNATE_DLL_AUTO: "create-drop"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health, liveness-state, readiness-state, prometheus
  MANAGEMENT_METRICS_WEB_SERVER_AUTO_TIME_REQUESTS: "true"