apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: spring-boot-database-credentials-secret
  namespace: airport-system
spec:
  encryptedData:
    SPRING_DATASOURCE_PASSWORD: AgB4IpwuYrZ33cbl4IwcJjGpsEsSGy4RF96jW+9nmUiHI7HUHz0JXgh1RJd5bC9mCAWS7hBC9zKVHlr3LbmgJSvEe6NczF/PuKcM0OR+jtTFr0EhQyI2bjU4uFkJLB1wnzvX17rCheWqxX5Z1z2eNkFp4ZQPs9+3T4axTJM6jkZfL6Fot/xb0vs1HpOGUkkWdzpLvvK3oY0Ul5HJgd9s7L1A8KQ5Yoe+r0sHk23LO5qSDOzpcJzNYyehHzmdxzqT0HEft6XfIgoNLEoHqpAowwMUCNXqUlhL0IAo5un9UgSmgMk4cnsAF0BAY0P79Za0Bt1/X1ysjQp5Czbt7SU6K92vnnr3hiYXDfGHYrrjHz2LQW7GvYmUOrTL2WA8/I8kIHtVAn+rQGK+P9QtWjOXH+BiDQGbv2pXjtsQP0+1BaXqhNRD08ZznaYbQbtfmlFoX93YrcvQbhDhYEebZ8THmIsSwYe1xWNA1YWgGR8yZrn42OKTR/0aMGwmCpVr8d3vtOaD+KZ3PGDHnA9DLVCIsj59UTKTxOARMtq9dFF+JDTe3tgnyVY4EXX9Sk4TucAOi27zSuhKUeeZP18UodjFgwxWYyO0QwbZopoKOk5gehrTbYZ2OEt+UZX3Zy2m1raUpAM4ot+NZ1WSTtxX8GEI35evhPjT5BChFlUlYfGnE/MYsRB0AHftUrc/b5hoFglI+7OSkqZajAhWd/SN48/clapamnkYbvv3wkYVfw==
    SPRING_DATASOURCE_USERNAME: AgBu0gtZkFCc+SdJy2cLDmKHLjkKV6Qz0cphVkADN3hOo/bVcDHvAOQlCCLizwCkS0VjdfhDrwJOxApdNftIFJOZgkYYJJhzSvNRbCa/oMDj9cIcmVlDsWM7oJMiM6QUMnoLHx/XP6+15nZ2qejpU4v08MWjlP4FjtnzF9jSjVK9d395cVeItf8yd9UysAT3uzzG00URGfIwk85TymIwPKvTvjdmKlBJCnnDt1nKAy4HcfzvXIyFLHLGMpdiUyNLOp30Xo37IhTZpGlYYGUV0eF4+iwCGMV0qGF7qVI+gXoRX0FDoJ7muhBklLkz+SmwcMWxySDgNDQgtB/nYEcokc5qkC4IQEZf43Yqr+yntKNsYAPUFVOb3tNxw0gPe+z2f2mTfmXAFApzN35uaO7AgCnbTvWE/Lcb4y7U/nFai5KuYGp3YRHz33YQ2zWSrWqPSUndWq+HKGour42q6WMry22Rdokf6nne3UC5dRVZhU5wP7WHlq11sQh6mw9gBIOW+UGcac8pejGRXZfnvQyoVqSCvMMdBJDeCh3KCp+YjHilvDQ9IbA7SunOBfuQ8DngQc9zTFDbQPi5FpCG3aqiLWFmJVHa3VtC1dGHhwb+/lXLwT4w4MseI8COnmyZL8T2WfUxsUoemNoDXz8OagljlO6efbogriwhj4GJhgjbLXSvy5ATHJhPD1A6N0orQWu5WafiQ+e0aQ==
  template:
    metadata:
      creationTimestamp: null
      name: spring-boot-database-credentials-secret
      namespace: airport-system

