kind: Deployment
apiVersion: apps/v1
metadata:
  name: plane
  namespace: airport-system
  labels:
    app: plane
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plane
  template:
    metadata:
      labels:
        app: plane
    spec:
      containers:
        - name: plane
          image: ghcr.io/joranbergfeld/airport-system-plane/plane:latest
          ports:
            - containerPort: 9000
              protocol: TCP
          resources: { }
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
