apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: plane
  name: plane
  namespace: airport-system
spec:
  port:
    targetPort: 9000-tcp
  to:
    kind: Service
    name: plane
    weight: 100
