apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: gate
  name: gate
  namespace: airport-system
spec:
  port:
    targetPort: 9001-tcp
  to:
    kind: Service
    name: gate
    weight: 100
