kind: Deployment
apiVersion: apps/v1
metadata:
  name: flight
  namespace: airport-system
  labels:
    app: flight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flight
  template:
    metadata:
      labels:
        app: flight
    spec:
      containers:
        - name: flight
          image: ghcr.io/joranbergfeld/airport-system-flight/flight:latest
          ports:
            - containerPort: 9003
              protocol: TCP
          resources: { }
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
