apiVersion: v1
kind: Service
metadata:
  labels:
    app: flight
  namespace: airport-system
  name: flight
spec:
  ports:
    - name: 9003-tcp
      port: 9003
      protocol: TCP
      targetPort: 9003
  selector:
    app: flight
  sessionAffinity: None
  type: ClusterIP
